// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ViewTable is an autogenerated mock type for the ViewTable type
type ViewTable struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ViewTable) Close() {
	_m.Called()
}

// Get provides a mock function with given fields: key
func (_m *ViewTable) Get(key string) (interface{}, error) {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Open provides a mock function with given fields:
func (_m *ViewTable) Open() {
	_m.Called()
}
